# Generated by Django 4.2.2 on 2023-07-01 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='static/EventsGallery')),
                ('Title', models.TextField(max_length=200)),
                ('StartDate', models.DateTimeField(default=datetime.datetime(2023, 7, 1, 12, 3, 44, 374957))),
                ('EndDate', models.DateTimeField(default=datetime.datetime(2023, 7, 1, 12, 3, 44, 374972))),
                ('Location', models.TextField(blank=True, max_length=200)),
                ('Description', models.CharField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryHeadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(max_length=200)),
                ('EventDate', models.DateTimeField(default=datetime.datetime(2023, 7, 1, 12, 3, 44, 375467))),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='static/images')),
                ('EventName', models.TextField(default='all', max_length=200)),
                ('EventDate', models.DateTimeField(default=datetime.datetime(2023, 7, 1, 12, 3, 44, 375249))),
            ],
        ),
        migrations.CreateModel(
            name='Sponsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='static/icons')),
                ('Link', models.CharField(blank=True, default='no link', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='static/images')),
                ('Name', models.TextField(max_length=200)),
                ('Position', models.TextField(max_length=50)),
                ('Twitter', models.CharField(blank=True, default='no link', max_length=5000)),
                ('Instagram', models.CharField(blank=True, default='no link', max_length=5000)),
                ('Linkedin', models.CharField(blank=True, default='no link', max_length=5000)),
                ('Year', models.IntegerField(max_length=100)),
            ],
        ),
    ]
