# Generated by Django 4.2.2 on 2023-07-01 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslist',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 12, 4, 0, 947355)),
        ),
        migrations.AlterField(
            model_name='eventslist',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 12, 4, 0, 947339)),
        ),
        migrations.AlterField(
            model_name='galleryheadings',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 12, 4, 0, 947909)),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 12, 4, 0, 947672)),
        ),
    ]
