# Generated by Django 4.2.2 on 2023-07-01 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_eventslist_enddate_alter_eventslist_startdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammembers',
            old_name='Position',
            new_name='Position_and_Year_of_study',
        ),
        migrations.AlterField(
            model_name='eventslist',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 18, 37, 3, 971955)),
        ),
        migrations.AlterField(
            model_name='eventslist',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 18, 37, 3, 971940)),
        ),
        migrations.AlterField(
            model_name='galleryheadings',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 18, 37, 3, 972453)),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 18, 37, 3, 972232)),
        ),
    ]
