# Generated by Django 4.2.2 on 2023-07-03 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_alter_eventslist_enddate_alter_eventslist_startdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslist',
            name='Register_Soon',
            field=models.TextField(default='Register or Soon', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventslist',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 3, 16, 1, 740338)),
        ),
        migrations.AlterField(
            model_name='eventslist',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 3, 16, 1, 740324)),
        ),
        migrations.AlterField(
            model_name='galleryheadings',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 3, 16, 1, 740844)),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 3, 16, 1, 740629)),
        ),
    ]
