# Generated by Django 4.2.2 on 2023-07-04 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_alter_eventslist_enddate_alter_eventslist_startdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='EventTitle',
            field=models.TextField(default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventslist',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 8, 21, 1, 529063)),
        ),
        migrations.AlterField(
            model_name='eventslist',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 8, 21, 1, 529049)),
        ),
        migrations.AlterField(
            model_name='galleryheadings',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 8, 21, 1, 529631)),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='EventDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 8, 21, 1, 529388)),
        ),
    ]
