# Generated by Django 4.2.2 on 2023-07-09 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0017_alter_eventslist_enddate_alter_eventslist_startdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniHeadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='static/images')),
                ('Name', models.TextField(max_length=60)),
                ('Position_and_Year_of_study', models.TextField(max_length=50)),
                ('Twitter', models.CharField(blank=True, default='no link', max_length=500)),
                ('Instagram', models.CharField(blank=True, default='no link', max_length=500)),
                ('Linkedin', models.CharField(blank=True, default='no link', max_length=500)),
                ('Year', models.TextField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='teamheadings',
            name='heading1',
        ),
        migrations.AlterField(
            model_name='eventslist',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 18, 42, 53, 699379)),
        ),
        migrations.AlterField(
            model_name='eventslist',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 18, 42, 53, 699363)),
        ),
        migrations.AlterField(
            model_name='galleryheadings',
            name='EventDate',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 18, 42, 53, 700011)),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='EventDate',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 18, 42, 53, 699782)),
        ),
    ]
