# Generated by Django 4.2.2 on 2023-07-09 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0021_alumniheadings_date_alter_eventslist_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnimembers',
            name='Quote',
            field=models.TextField(blank=True, default='No Quote', max_length=100),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Quote',
            field=models.TextField(blank=True, default='No Quote', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumniheadings',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 19, 6, 35, 884717)),
        ),
        migrations.AlterField(
            model_name='eventslist',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 19, 6, 35, 883182)),
        ),
        migrations.AlterField(
            model_name='eventslist',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 19, 6, 35, 883160)),
        ),
        migrations.AlterField(
            model_name='galleryheadings',
            name='EventDate',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 19, 6, 35, 883777)),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='EventDate',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 19, 6, 35, 883527)),
        ),
        migrations.AlterField(
            model_name='teamheadings',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 19, 6, 35, 884270)),
        ),
    ]
