# Generated by Django 5.0.2 on 2024-03-17 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0027_alter_alumniheadings_date_alter_eventslist_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniheadings',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 3, 17, 18, 4, 19, 846574)),
        ),
        migrations.AlterField(
            model_name='eventslist',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 18, 4, 19, 844868)),
        ),
        migrations.AlterField(
            model_name='galleryheadings',
            name='EventDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 17, 18, 4, 19, 845466)),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='EventDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 17, 18, 4, 19, 845218)),
        ),
        migrations.AlterField(
            model_name='teamheadings',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 3, 17, 18, 4, 19, 846043)),
        ),
    ]
