# Generated by Django 5.0.3 on 2024-03-18 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0029_alter_alumniheadings_date_alter_eventslist_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniheadings',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 7, 40, 41, 916206)),
        ),
        migrations.AlterField(
            model_name='eventslist',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 7, 40, 41, 914562)),
        ),
        migrations.AlterField(
            model_name='galleryheadings',
            name='EventDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 7, 40, 41, 915123)),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='EventDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 7, 40, 41, 914895)),
        ),
        migrations.AlterField(
            model_name='teamheadings',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 7, 40, 41, 915639)),
        ),
    ]
