# Generated by Django 5.0.3 on 2024-03-18 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0033_alter_alumniheadings_date_alter_eventslist_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniheadings',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 7, 59, 42, 458387)),
        ),
        migrations.AlterField(
            model_name='eventslist',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 7, 59, 42, 456708)),
        ),
        migrations.AlterField(
            model_name='galleryheadings',
            name='EventDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 7, 59, 42, 457251)),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='EventDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 7, 59, 42, 457030)),
        ),
        migrations.AlterField(
            model_name='teamheadings',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 7, 59, 42, 457782)),
        ),
    ]
